/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PilihanDokter;

/**
 *
 * @author Zhabiyan
 */
public class PilihDokter extends javax.swing.JFrame {

    /**
     * Creates new form PilihDokter
     */
    public PilihDokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        spesial = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        usia = new javax.swing.JTextField();
        jenis = new javax.swing.JTextField();
        gol = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        kewar = new javax.swing.JTextField();
        waktu = new javax.swing.JTextField();
        jconadokt = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Pemilihan Dokter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 0, 260, 30);

        jLabel2.setText("Dokter Spesialis");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 450, 130, 20);

        jLabel3.setText("Pilih Dokter");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 50, 140, 20);

        jLabel4.setText("Nama");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 140, 20);

        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 170, 140, 20);

        jLabel6.setText("Usia");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 210, 140, 20);

        jLabel7.setText("Jenis Kelamin");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 250, 140, 20);

        jLabel8.setText("Golongan Darah");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 290, 140, 20);

        jLabel9.setText("Status");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 330, 130, 20);

        jLabel10.setText("Kewarganegaraan");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 370, 130, 20);

        jLabel11.setText("Waktu Praktek");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 410, 130, 20);
        getContentPane().add(spesial);
        spesial.setBounds(190, 440, 240, 30);
        getContentPane().add(nama);
        nama.setBounds(190, 120, 240, 30);
        getContentPane().add(alamat);
        alamat.setBounds(190, 160, 240, 30);
        getContentPane().add(usia);
        usia.setBounds(190, 200, 240, 30);
        getContentPane().add(jenis);
        jenis.setBounds(190, 240, 240, 30);
        getContentPane().add(gol);
        gol.setBounds(190, 280, 240, 30);
        getContentPane().add(status);
        status.setBounds(190, 320, 240, 30);
        getContentPane().add(kewar);
        kewar.setBounds(190, 360, 240, 30);
        getContentPane().add(waktu);
        waktu.setBounds(190, 400, 240, 30);

        jconadokt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DR. Farras Yassar", "DR. Dian Sikahita", "DR. Harun Ulum Fajar" }));
        jconadokt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconadoktActionPerformed(evt);
            }
        });
        getContentPane().add(jconadokt);
        jconadokt.setBounds(160, 40, 150, 30);

        jLabel12.setText("Identitas");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 90, 160, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jconadoktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconadoktActionPerformed
        if(jconadokt.getSelectedItem().equals("DR. Farras Yassar")){
            nama.setText("DR. Farras Yassar ");
            alamat.setText("Jl. Surabaya 16, Malang");
            usia.setText("20 Tahun");
            jenis.setText("Laki-Laki");
            gol.setText("A");
            status.setText("Belum Menikah ");
            kewar.setText("Indonesia");
            spesial.setText("Dokter Umum");
            waktu.setText(" Pagi (07.00-15.00)");
        }
        else
        if(jconadokt.getSelectedItem().equals("DR. Dian Sikahita")){
            nama.setText("DR. Dian Sikahita");
            alamat.setText("Jl. Veteran 3, Malang");
            usia.setText("20 Tahun");
            jenis.setText("Perempuan");
            gol.setText("O");
            status.setText("Belum Menikah");
            kewar.setText("Indonesia");
            spesial.setText("Dokter Gigi");
            waktu.setText(" Sore (16.00-22.00)");
        }
        else
        if(jconadokt.getSelectedItem().equals("DR. Harun Ulum Fajar")){
            nama.setText("DR. Harun Ulum Fajar");
            alamat.setText("Jl. Bandung 9, Malang");
            usia.setText("20 Tahun");
            jenis.setText("Laki-Laki");
            gol.setText("B");
            status.setText("Belum Menikah");
            kewar.setText("Indonesia");
            spesial.setText("Dokter Gizi");
            waktu.setText(" Malam (22.00-06.00)");
        }
    }//GEN-LAST:event_jconadoktActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihDokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField gol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jconadokt;
    private javax.swing.JTextField jenis;
    private javax.swing.JTextField kewar;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField spesial;
    private javax.swing.JTextField status;
    private javax.swing.JTextField usia;
    private javax.swing.JTextField waktu;
    // End of variables declaration//GEN-END:variables
}
